[project]
name = "sheetcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tommy", email = "tommytty@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.198.0",
    "google-auth>=2.56.2",
    "mcp>=2.0.0,<3.0.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
sheetcode = "sheetcode:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]
